### ISSUE TITLE
How to add grid movement cost

### ISSUE THREAD

**Issue by dingjia123** [Sana-078/Pathfinding-Visualizer#1]
Thank you for your work, it is very useful to me. I have a need and need your help: add the moving cost of the square. At present, the default step length of the white square is 1, and the black square is set as an obstacle. How to add a square with a step length of 2, 5, 10 or other values (the path can pass through this square, but the number of steps used is not the default value 1). For example, add a gray square with a step of 5? The advantage of this is that it can highlight the difference between the Dijkstar algorithm and the BFS algorithm.
Looking forward to hearing from you.

**Comment by dingjia123** [comment]
as the green area in the picture. @Sana-078 
![1](https://user-images.githubusercontent.com/45927176/138271465-ecc90586-35c5-43a9-88ef-9dea3c540c67.png)

**Comment by Shame-fight** [comment]
> Thank you for your work, it is very useful to me. I have a need and need your help: add the moving cost of the square. At present, the default step length of the white square is 1, and the black square is set as an obstacle. How to add a square with a step length of 2, 5, 10 or other values (the path can pass through this square, but the number of steps used is not the default value 1). For example, add a gray square with a step of 5? The advantage of this is that it can highlight the difference between the Dijkstar algorithm and the BFS algorithm. Looking forward to hearing from you.

I have the same request,could you help us?  thanks @Sana-078

**Comment by Sana-130** [comment]
Thank you for posting this issue and going through my code @Shame-fight  @dingjia123. 
@dingjia123 like you asked , I tried to implement weighted graph (I used random numbers as weights for each cell).  I gave distance(weight) as an instance attribute to the Spot class and by that way I can display them over the cell using text.

The code is pretty much same except the line 247:
where we do "temp_dist=distance[current] + 1"
replace 1 with grid[row][col].distance

I modified the code a bit , I though I would post them in a different file. I have not yet added the feature of barriers in it because click events are taking some time to respond,  I guess its because of adding text above the rectangle. So I hardcoded the start and end coordinates by myself.
 
By far this is what I got.
![Screenshot (84)](https://user-images.githubusercontent.com/70009983/138546543-dcc5ec1a-f970-488b-a23b-f027427f6571.png)

hope this helps.🙂

**Comment by dingjia123** [comment]
Thank you for your hard work, I read your changes. There are two suggestions
1. Compared to randomizing the cost of all map grids, I am more concerned with increasing the cost for a specific grid, rather than all (for example, when a specific area simulates grass, the cost will increase when passing through this area). what do you think?
2. Adding obstacles
Thanks for your reply, if you have plans to modify the code, please let me know. I like your project
@Sana-078

**Comment by Sana-130** [comment]
Yeah so, Let me get this straight. The grid might have a portion of cells in green color representing grass, which have larger movement cost rather than the other cells, lets say random number between 10 to 20 while others have a value between 1 to 5 . User can specify this green area on their own (that's how I did it now, they can right click on the cell for that , left clicking will do the start , end and barrier nodes, In the previous program, the right mouse click was used to erase or reset the color, Now that we are using right click for green cells , I have given specific keyboard commands to erase  each one of them.
s - resetting start and end node,
b- ""   barrier nodes
g- ""  grass nodes
space bar- "" visualization part
c- "" clear everything)
If you have a better way,  go ahead with it.

Right now, this is how it looks:
![wdj](https://user-images.githubusercontent.com/70009983/138681399-a996faad-d0a4-4a42-a06d-7d63cb47f168.png)

Also I was able to catch the reason behind the lagging ,  turns out I was creating the pygame.font.Font object in every frame , so I fixed that and everything was running smoothly.
If you wanna play around with the cost of some specific cells like in the picture above (the one that you posted), you can always edit the distance value of the cells inside the Dijkstra function before the while loop starts. 

By the way let me know if I got anything wrong or missed anything. Happy to help .🤝 @dingjia123
